### PR TITLE
Comments

### PR DESCRIPTION
**Pull request by cjudge1337**
Top level comments can be successfully submitted now. It'll update the store's comments after submit but it's random from the API whether the new comment will show up or not.

### CODE REVIEW

**Review by davidhu2000 — CHANGES_REQUESTED** [review]
can you remove `yarn-error.log` file from your commits? Also, there are some linting errors, just run `yarn run lint` in your terminal to see what they are

**Comment by cjudge1337** [comment]
Done. Line 38 in `comments.jsx` where `<NewComment>` gets rendered is kind of awkward stylistically.

**Comment by davidhu2000** [comment]
can you add some feedback for when the user click the box to comment? Like, render a `comment` button, just like the real Youtube. 

Make sure to `git pull` before you start working, I made a commit to fix some linting errors.

**Comment by cjudge1337** [comment]
Works like youtube comment buttons now, they need some styling.

**Review by davidhu2000 — APPROVED** [review]

**Pull request merged**
